blank_issues_enabled: true
contact_links:
  - name: Features, Bug Reports, Questions
    url: https://github.com/poperigby/barnacle/discussions/new/choose
    about: Our preferred starting point if you have any questions or suggestions about configuration, features, or behaviour.
